sudo: required
services:
  - docker

before_install:
  - docker build -t italoferreira/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true italoferreira/udemy-docker-react npm run test -- --coverage