sudo: required
services:
  - docker

before_install:
  - docker build -t italoferreira/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true italoferreira/udemy-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "udemy-docker-react"
  env: "UdemyDockerReact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-052664762717"
  bucket_path: "udemy-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY